name: build-emias-lite
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npx electron-builder install-app-deps
      - run: npm run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - uses: actions/upload-artifact@v4
        with:
          name: emias-lite-dist
          path: dist/**
