name: release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - run: npm ci
      - run: npx electron-builder install-app-deps
      - run: npm run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

      - name: Archive dist
        run: |
          powershell -Command "Compress-Archive -Path dist\* -DestinationPath dist.zip -Force"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist.zip
            dist\*.exe
            dist\*.msi
            dist\*.zip
            dist\*.7z
